name: CI

on:
  push:
    branches: [develop, 'feature/*', 'release/*', 'hotfix/*']
  pull_request:
    branches: [develop, 'release/*']

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.5'
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Rodar testes
        run: |
          python -m unittest discover tests
