name: Release

on:
  push:
    branches: [main]

jobs:
  build-test-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.5'
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Rodar testes
        run: |
          python -m unittest discover tests
      - name: Gerar Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v0.1.0
          name: "Release 0.1.0"
          body_path: ./CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
